sudo: true

language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

    packages:
      - gcc
      - g++
      - clang
      - curl
      - python-dev
      - python3-pip
      - python-virtualenv

install:
  - ./install.sh
