version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  format:
    docker:
      - image: node:18
    resource_class: large
    parallelism: 10

    steps:
      - checkout
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install pnpm package manager
          command: |
            curl -L https://pnpm.js.org/pnpm.js | node - add --global pnpm@7
      - run:
          name: Install Dependencies
          command: |
            pnpm install
      - run:
          name: Run Prettier
          command: |
            pnpm prettier --write .
      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules

  build-evm:
    docker:
      - image: python:3.9-alpine
    resource_class: large
    parallelism: 10

    steps:
      - checkout
      - run:
          name: install deps
          command: pip install -r requirements.txt

      - run:
          name: build
          command: chmod +x ./build.sh && ./build.sh
workflows:
  format:
    jobs:
      - format  
  build-evm:
    jobs:
        - build-evm    
