name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  evm:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
