name: format

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  evm:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - uses: pnpm/action-setup @v6.24.1

        with:
          version: 6.0.2

      - run: pnpm install
      - run: pnpm prettier --write .
